### ISSUE TITLE
Update Mapbox dependency to Nav 2.0

### ISSUE THREAD

**Issue by kavalerov** [ably/ably-asset-tracking-cocoa#106]
Mapbox have just released  a new version of their SDK: https://www.mapbox.com/blog/on-device-routing-flexible-and-versatile-camera-mapbox-navigation-sdk-v2

The part that is relevant to us is lower battery and network consumptions. 

We need to asses wether it introduces any breaking changes to our integration, and update the dependency.

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-729) by [Unito](https://www.unito.io)

**Comment by ben-xD** [comment]
It also adds Swift package manager support, so only once we do this, can we also support SPM.

**Comment by ben-xD** [comment]
There was only one breaking change: `startUpdatingLocation` is now synchronous so there is no callback. See [change log](https://github.com/mapbox/mapbox-navigation-ios/releases/tag/v2.0.0-alpha.3) for v2.0.0-alpha.3 here

> Renamed PassiveLocationManager.startUpdatingLocation(completionHandler:) to PassiveLocationManager.startUpdatingLocation(). This method now runs synchronously like CLLocationManager.startUpdatingLocation(). (#2823)
