### ISSUE TITLE
Remove EXCLUDED_ARCHS entry from pods post_install script

### ISSUE THREAD

**Issue by mmiedlarz** [ably/ably-asset-tracking-cocoa#40]
There is a [MapBox issue](https://github.com/mapbox/mapbox-navigation-ios/issues/2674) which forced us to add the following post_install hook to be able to run example app on physical device:
```
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
  end
end
```
The issue here is that it will cause the build to fail on the iOS simulator when compiled on Mac with M1 CPU.
So far it's not a huge problem, but we need to fix it as soon as the MapBox team releases the new framework version.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-745) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
This issue end up obsoleted by https://github.com/ably/ably-asset-tracking-cocoa/issues/106.

**Comment by ben-xD** [comment]
> This issue should end up being obsoleted by #106.

Closing because I upgraded to mapbox v2.0, tested everything is working. https://github.com/ably/ably-asset-tracking-cocoa/pull/152
